### ISSUE TITLE
Reseting a branch takes a bit of time to settle, during which results are incorrect and throw errors

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakefs-iceberg#25]
1. Delete the contents of a table and then reset the branch
2. SYMPTOM 01: the row count stays at zero
3. SYMPTOM 02: you get a `Metadata file for version x is missing` error if you try to run the delete again
4. Wait for _a period of time_ (I used 1 minute in testing)
5. Row count is now correct
6. Delete now works

See steps to reproduce below.

### Current table row count

```sql
%%sql

SELECT COUNT(*) FROM lakefs.dev.rmoff.my_table;
```

<table>
    <thead>
        <tr>
            <th>count(1)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>2</td>
        </tr>
    </tbody>
</table>

## Delete the contents of the table

```python
%sql DELETE FROM lakefs.dev.rmoff.my_table
```

<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

```python
%sql SELECT COUNT(*) from lakefs.dev.rmoff.my_table
```

<table>
    <thead>
        <tr>
            <th>count(1)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>0</td>
        </tr>
    </tbody>
</table>

## Reset the branch

```python
lakefs.branches.diff_branch(repo.id, "dev").results
```

    [{'path': 'rmoff/my_table/metadata/97e91ecd-8063-4cc1-8769-6f5ea5ba8ef6-m0.avro',
      'path_type': 'object',
      'size_bytes': 1,
      'type': 'added'},
     {'path': 'rmoff/my_table/metadata/snap-8760018757477333873-1-97e91ecd-8063-4cc1-8769-6f5ea5ba8ef6.avro',
      'path_type': 'object',
      'size_bytes': 1,
      'type': 'added'},
     {'path': 'rmoff/my_table/metadata/v3.metadata.json',
      'path_type': 'object',
      'size_bytes': 1,
      'type': 'added'},
     {'path': 'rmoff/my_table/metadata/version-hint.text',
      'path_type': 'object',
      'size_bytes': 1,
      'type': 'changed'}]

```python
lakefs.branches.reset_branch(repo.id, 
                             "dev",
                             ResetCreation(type="reset"))
```

```python
lakefs.branches.diff_branch(repo.id, "dev").results
```

    []

## ❌ There should be two rows in the table now because we've reset the branch but it shows zero

```python
%sql SELECT COUNT(*) from lakefs.dev.rmoff.my_table
```

<table>
    <thead>
        <tr>
            <th>count(1)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>0</td>
        </tr>
    </tbody>
</table>

## ❌ Running a delete fails

```python
import traceback

try:
    spark.sql("DELETE FROM lakefs.dev.rmoff.my_table")
except Exception as e:
    # print the exception message and stack trace
    print(f"An error occurred: {str(e)}")
    # traceback.print_exc()
```

    An error occurred: An error occurred while calling o49.sql.
    : org.apache.iceberg.exceptions.ValidationException: Metadata file for version 3 is missing
    	at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:111)
    	at org.apache.iceberg.SnapshotProducer.refresh(SnapshotProducer.java:345)
    	at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:210)
    	at org.apache.iceberg.StreamingDelete.apply(StreamingDelete.java:30)
    	at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:366)
    	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
    	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
    	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
    	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
    	at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:364)
    	at org.apache.iceberg.StreamingDelete.commit(StreamingDelete.java:30)
    	at org.apache.iceberg.spark.source.SparkTable.deleteWhere(SparkTable.java:378)
    	at org.apache.spark.sql.execution.datasources.v2.DeleteFromTableExec.run(DeleteFromTableExec.scala:31)
    	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
    	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
    	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
    	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
    	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
    	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
    	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
    	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
    	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
    	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
    	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
    	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
    	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
    	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
    	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
    	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
    	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
    	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
    	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
    	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
    	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
    	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
    	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
    	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:220)
    	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
    	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
    	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
    	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:622)
    	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
    	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:617)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    	at py4j.Gateway.invoke(Gateway.java:282)
    	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    	at py4j.commands.CallCommand.execute(CallCommand.java:79)
    	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
    	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
    	at java.base/java.lang.Thread.run(Thread.java:833)
    

## Let's wait awhile for things to right themselves _automagically_ 🧙🏻🪄👻

```python
from time import sleep

sleep(60)
```

## Now the same statements as above work just fine… ¯\\_(ツ)_/¯

```python
%sql SELECT COUNT(*) from lakefs.dev.rmoff.my_table
```

<table>
    <thead>
        <tr>
            <th>count(1)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>2</td>
        </tr>
    </tbody>
</table>

```python
%sql DELETE FROM lakefs.dev.rmoff.my_table
```

<table>
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

```python
%sql SELECT COUNT(*) from lakefs.dev.rmoff.my_table
```

<table>
    <thead>
        <tr>
            <th>count(1)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>0</td>
        </tr>
    </tbody>
</table>

**Comment by johnnyaug** [comment]
Same as in #27, see my [comment](https://github.com/treeverse/lakefs-iceberg/issues/27#issuecomment-1620096316) there.
Suggest to close this one as well.

**Comment by rmoff** [comment]
closing as dup of #27
